### ISSUE TITLE
How to hook?

### ISSUE THREAD

**Issue by usama7628674** [cutesunshine/HookTaskmgr#1]
After compilation theres only hook.dll so how can i use it to hide process from taskmanager?
Do i need a tool to inject hook.dll into taskmanager using doubleagent?

Also x64 Release does not compile.
![Capture](https://user-images.githubusercontent.com/29252277/66447569-1fa64700-ea68-11e9-9962-fa78c9bb4e70.PNG)

**Comment by dingtao1** [comment]
@usama7628674 Have you implemented this function?
